Add block for a tea timer (or any timer, really)
greshake/i3status-rust pull request #1651
Opened 2022-10-29 21:57 UTC by isottellina

Timer for a general timer, that adds 30s each time you click on it. I did it for my personal use, don't hesitate to close the PR if you think it has no place upstream.

2022-12-14 07:03 UTC, MaxVerevkin requested changes
Sorry for late response. The PR looks good to me and I like the idea. Please add icons for other icon sets.

By the way, maybe right click should reset the timer?

2022-12-14 08:42 UTC, isottellina commented
> Sorry for late response. The PR looks good to me and I like the idea. Please add icons for other icon sets.
> 
> By the way, maybe right click should reset the timer?

Not a bad idea, done

2022-12-14 18:34 UTC, MaxVerevkin commented
Similarly, wheel up/down can be used to increment/decrement the timer.

2022-12-14 19:01 UTC, isottellina commented
> Similarly, wheel up/down can be used to increment/decrement the timer.

Done too

2022-12-14 19:18 UTC, MaxVerevkin approved these changes

2022-12-14 19:43 UTC, isottellina commented on src/blocks/tea_timer.rs
> +        api.set_widget(&widget).await?;
I think there is. I did a thing, lmk if that's good for you

2022-12-14 19:50 UTC, MaxVerevkin commented on src/blocks/tea_timer.rs
> +        api.set_widget(&widget).await?;
Perfect!

2022-12-14 19:56 UTC, MaxVerevkin commented
A also think it might be a good idea to add an option to hide `00:00` when timer is inactive. Either by adding `format_inactive` or by omitting `hours`/`minutes`/`seconds` placeholders when they're all zero (then you can have ` $icon {$minutes:$seconds |}` to hide zeros or ` $icon {$minutes:$seconds|00:00} ` to show them).

2022-12-14 20:04 UTC, isottellina commented
> A also think it might be a good idea to add an option to hide `00:00` when timer is inactive. Either by adding `format_inactive` or by omitting `hours`/`minutes`/`seconds` placeholders when they're all zero (then you can have ` $icon {$minutes:$seconds |}` to hide zeros or `$icon {$minutes:$seconds|00:00}` to show them).

Great idea, done

2022-12-14 20:05 UTC, MaxVerevkin commented
And please add a note in the docs about this behavior

2022-12-14 20:07 UTC, MaxVerevkin commented on src/blocks/tea_timer.rs
> +    let format = config.format.with_default(" $icon {$minutes:$seconds|} ")?;
To avoid double spaces:
```suggestion
    let format = config.format.with_default(" $icon {$minutes:$seconds |}")?;
```

2022-12-14 20:19 UTC, isottellina commented
The pre-condition on the select introduced the bug of timers being set at Durations inferior to the interval, due to having evaluated `now` several seconds, or more, prior. Fixing this too.

2022-12-18 17:58 UTC, MaxVerevkin commented
Thanks!

2022-12-18 17:58 UTC, merged

2023-03-13 11:48 UTC, c02y commented
Would you please make it possible to be longer than 60 minutes?

2023-03-13 12:23 UTC, isottellina commented
> Would you please make it possible to be longer than 60 minutes?
> 
> Another suggestion: middle click to change format, which can set exactly time to notify instead of count down.

You can currently make it last longer than 60 minutes, the hours just aren't displayed if you haven't set the $hours to be displayed in the format. For any other suggestions, I think the issues might be a more suitable place.

2023-03-13 12:29 UTC, c02y commented
Would you please make it possible to be longer than 60 minutes?

> > Would you please make it possible to be longer than 60 minutes?
> > Another suggestion: middle click to change format, which can set exactly time to notify instead of count down.
> 
> You can currently make it last longer than 60 minutes, the hours just aren't displayed if you haven't set the $hours to be displayed in the format. For any other suggestions, I think the issues might be a more suitable place.


Sorry about that, how stupid I am, simply followed the config example but didn't read the full doc.