Fix spacing for inline widgets
greshake/i3status-rust pull request #866
Opened 2020-10-15 04:08 UTC by DCsunset

I have added a spacing setting for each widget that can control the spacing.
The `Inline` setting will remove the leading space, which is very useful for sub-widget in some blocks.
The `Hidden` setting will remove both the leading space and trailing space, which is useful for hidden blocks.

To demonstrate the usage, I have also fixed the spacing for `nvidia_gpu` block.

This PR should resolve the issue #800.

2020-10-15 04:42 UTC, ammgws commented
Can you paste the before and after nvidia-gpu block output here (i.e. the raw output from i3status-rs when run from a commandline)?

2020-10-15 04:45 UTC, ammgws requested changes

2020-10-15 04:45 UTC, ammgws commented on src/widget.rs
> +    /// Hide all spaces when the widget is hidden
Just to make it clearer: "Hide both leading and trailing spaces when widget is hidden"

2020-10-15 04:45 UTC, ammgws commented on src/widget.rs
> +    Normal,
Just to make it clearer: "Adds a leading and trailing space around the widget contents"

2020-10-15 05:01 UTC, DCsunset commented
Before:

```json
{"background":"#000000FF","color":"#CCCCCCFF","full_text":"  GeForce MX150 ","markup":"pango","name":"f6a82f89f0f241dd838918b61a6deb6c","separator":false,"separator_block_width":0},
{"background":"#000000FF","color":"#CCCCCCFF","full_text":" 0 % ","separator":false,"separator_block_width":0},
{"background":"#000000FF","color":"#CCCCCCFF","full_text":" 52°C ","separator":false,"separator_block_width":0}
```

After:

```json
{"background":"#000000FF","color":"#CCCCCCFF","full_text":"  GeForce MX150 ","markup":"pango","name":"547e37d81bae45cd9e96ecfc4713ac12","separator":false,"separator_block_width":0},
{"background":"#000000FF","color":"#CCCCCCFF","full_text":"0 % ","separator":false,"separator_block_width":0},
{"background":"#000000FF","color":"#CCCCCCFF","full_text":"41°C ","separator":false,"separator_block_width":0}
```

Leading spaces of both the temperature and utilization are removed.
Besides, when the name of the GPU is hidden, its trailing spaces will also be removed.

2020-10-15 05:09 UTC, DCsunset commented
I have also fixed the comment and squash it into the first commit.

2020-10-15 06:40 UTC, ammgws commented
Can you please apply this to the other blocks as well? Might as well fix them all at once.

2020-10-16 23:49 UTC, ammgws approved these changes

2020-10-16 23:49 UTC, ammgws requested changes
Apply to other blocks as well. Might as well fix them all at once.

2020-10-19 02:20 UTC, DCsunset commented
I have fixed some blocks that I found with inconsistent spacing. Are there other blocks that need fixing as well?

2020-10-19 02:26 UTC, ammgws commented
IIRC one would be the music block (the buttons at least).

2020-10-19 04:32 UTC, ammgws approved these changes

2020-10-19 04:32 UTC, ammgws commented
We can handle those in another PR

2020-10-19 04:33 UTC, merged